### ISSUE TITLE
>meme arrow

### ISSUE THREAD

**Issue by RafaelCS-Aula** [RafaelCS-Aula/test#1]

**Comment by RafaelCS-Aula** [comment]
asdasd

**Comment by Jtoliveira** [comment]
This is a test comment

**Comment by RafaelCS-Aula** [comment]
I said WE CLOSED

**Comment by Jtoliveira** [comment]
![image](https://user-images.githubusercontent.com/48063454/122438652-d6273280-cf92-11eb-8ead-1df45c76b95d.png)
